---
title: "EncodeClassesAsProb"
author: "Jean-Francois Chartier"
date: "15 mars 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Read data.frame mood.industry.data.rds
```{r}
mood.industry.data=readRDS("mood.industry.data.rds")
prediction.on.test.set=readRDS("hierar.RF.prediction.on.test.set.rds")
new.annotation=read.csv(file = "hierar_lr2.csv", header = T, strip.white = T, blank.lines.skip = T, stringsAsFactors = F, encoding = "UTF-8")
```


#prepare classification labels
```{r}
negative.class=(data.classification$label_of_class=="no_comment" | data.classification$label_of_class=="no_consultation" |  data.classification$label_of_class=="no_statement")

binary.label=character(length = length(negative.class))
binary.label[negative.class]="is.not.consultation.label"
binary.label[negative.class==F]="is.consultation.label"


```



#encode training set classes as probability
```{r}
idTain=which(mood.industry.data$training.set==T)
mood.industry.data

```


```{r}
idTest=which(mood.industry.data$training.set==F)
```




##retrieve id row from master DF
```{r}

apply(mood.industry.data[mood.industry.data$training.set==F, c(1:5)], MARGIN = 1, function(exemp){
  i=apply(new.annotation[,c(1:5)], MARGIN = 1, function(x) identical(exemp, x))
  #print(i)
  new.annotation[i, ]
})->x
#new.annotation
```
